quarkus:
  http:
    port: 8081
    test-port: 8082
  application:
    name: Foodhouse service
    version: ${FOODHOUSE_VERSION}
  console:
    color: true
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    reactive:
      url: postgresql://${DB_HOST}:5432/slurpanize_db
      max-size: 20

# => OpenAPI settings
mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Foodhouse service
          version: ${FOODHOUSE_VERSION}
          description: Set of services to serve and store Foodhouse (aka Merchant, Restoraunt, Food truck) information data

"%dev":
  quarkus:
    http:
      cors: true